name: GridCapa acceptance tests

on:
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    environment:
      name: GridCapa K8S
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_BASE_URL: ${{ secrets.GRIDCAPA_TESTS_BASE_URL }}
          CYPRESS_GRIDCAPA_FB_USER: ${{ secrets.GRIDCAPA_FB_USER }}
          CYPRESS_GRIDCAPA_FB_PASSWORD: ${{ secrets.GRIDCAPA_FB_PASSWORD }}
          CYPRESS_GRIDCAPA_FTP_HOST: ${{ secrets.GRIDCAPA_FTP_HOST }}
          CYPRESS_GRIDCAPA_FTP_USER: ${{ secrets.GRIDCAPA_FTP_USER }}
          CYPRESS_GRIDCAPA_FTP_PASSWORD: ${{ secrets.GRIDCAPA_FTP_PASSWORD }}
          CYPRESS_GRIDCAPA_MINIO_USER: ${{ secrets.GRIDCAPA_MINIO_USER }}
          CYPRESS_GRIDCAPA_MINIO_PASSWORD: ${{ secrets.GRIDCAPA_MINIO_PASSWORD }}
          TZ: Europe/Brussels

      - name: Upload videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
